### ISSUE TITLE
Probando

### ISSUE THREAD

**Issue by osfa-trece** [Fablab-Sevilla/ghPython101#1]
Subí los primeros archivos... Entiendo que están ya en el repositorio online - aunque no me aclaro del todo qué está online-remoto y qué en local :-)
Mañana volveré a preguntar por el pull request - de momento no lo he tocado - creo que ea algo del admin, no?
Salud!

**Comment by angellinares** [comment]
Buenas!, si has hecho e commit y le has dado a Sync (suponiendo que estés trabajando en local ya en la rama D_001) lo que has hecho está online, pero déjame mirarlo.

**Comment by angellinares** [comment]
Si te fijas en la captura, aparece tu commit en la rama D_001, por lo que lo has hecho bien ;)

![image](https://cloud.githubusercontent.com/assets/2106720/11096772/0a813bb4-889c-11e5-8950-f31be2c1016d.png)

**Comment by osfa-trece** [comment]
ok, gracias Ángel, había intentando subir tb los archivos gh - voy a ver qué ha pasado, es posible que no haya hecho previamente commit... ? O que sea algo con el ignore...?

**Comment by angellinares** [comment]
Has hecho dos commit:
![Uploading image.png…]()

Fíjate que aparecen dos

**Comment by angellinares** [comment]
[Has hecho dos commit](https://github.com/Fablab-Sevilla/ghPython101/commits/D_001), y por lo que veo, [en uno de ellos](https://github.com/Fablab-Sevilla/ghPython101/commit/609c3f28240c57cd537ce5185bb93c525f3e4ee5) se han subido los archivos de GH.

**Comment by osfa-trece** [comment]
Bueno, ahora creo que he metido la pata... me parece que he hecho merge de nuestro branch de d001 con el master :-S _ lo siento...

**Comment by angellinares** [comment]
Jajajajaja, eso no puede ser, y por lo que veo no es así, no sé qué ves en local tu, pero te aseguro que no has hecho ningún merge...la rama Master la tengo protegida :dancer: . Mañana lo vemos, pero lo que has hecho creo que ha sido simplemente mover los archivos. Tu deja tu cliente en la rama D_001 y trabaja ahí (que me suena que has cambiado la rama en el cliente a lo mejor y eso te ha rayado) ;)

**Comment by osfa-trece** [comment]
ok... Mañana vemos, me alegro de que no haya pasado nada... ya te enseño...

**Comment by angellinares** [comment]
Te vamos a coronar @osfa-trece el destructor de mundos...

![Osfa](http://vignette1.wikia.nocookie.net/godzilla/images/a/a8/Concept_Art_-_Godzilla_2000_Millennium_-_Yuji_Sakai's_Godzilla_2.png/revision/latest?cb=20140705045725)
